export * from './homepage';
export * from './login.page';
export * from './main.page';
export * from './register.page';
export * from './settings.page';
export * from './yourfeed.page';
export * from './article.creation.page';
export * from './article.review.page';
export * from './app.page';